language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls
  - php vendor/bin/coveralls -v    


notifications:
  email:
    on_success: never
    on_failure: always
