language: php


php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

addons:
  postgresql: "9.3"

before_script:
  - composer selfupdate
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - composer install --dev --no-interaction
  - psql -c 'create database cti_storage_tests;' -U postgres;
  - cp tests/resources/php/travis.config.php tests/resources/php/local.config.php

script:
  - php vendor/bin/phpunit -c phpunit.xml.dist

after_script:
  - php vendor/bin/coveralls


notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  allow_failures:
    - php: hhvm